version: "3.7"

services:
  db:
    image: mariadb:10.2
    volumes:
      - db-data-${WORDPRESS_VERSION:-5.5.0}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    image: ziodave/wordpress-xdebug:5.8.3-php8.0
    depends_on:
      - db
    volumes:
      - wordpress-data-${WORDPRESS_VERSION:-5.5.0}:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/wordlift
      - ../pods:/var/www/html/wp-content/plugins/pods
      - ../pods-export-code:/var/www/html/wp-content/plugins/pods-export-code
#      - ../advanced-custom-fields-for-schema-org:/var/www/html/wp-content/plugins/advanced-custom-fields-for-schema-org
      - ../woocommerce:/var/www/html/wp-content/plugins/woocommerce
      - ./.docker/php/etc/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        # Add support for the reverse proxy.
        if ( strpos( $$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https' ) !== false ) {
        	$$_SERVER['HTTPS'] = 'on';
        }

        if ( isset( $$_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {
          $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST'];
        }

        # Define the site and home URLs.
        define( 'WP_SITEURL', 'https://wordlift.localhost' );
        define( 'WP_HOME', WP_SITEURL );

        # Allow all entity types.
        # define( 'WL_ALL_ENTITY_TYPES', true );

        # Enable Debug logging to the /wp-content/debug.log file
        define( 'WP_DEBUG_LOG', true );
        # Disable display of errors and warnings
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 0 );
        # Use dev versions of core JS and CSS files (only needed if you are modifying these core files)
        define( 'SCRIPT_DEBUG', true );

        # Enable WordLift debug.
        define( 'WL_DEBUG', WP_DEBUG );
        define( 'WL_LOG_LEVEL', 0 );
        define( 'WP_AUTO_UPDATE_CORE', false );
        add_filter('wl_feature__enable__pods-integration', '__return_true' );
      PHP_IDE_CONFIG: serverName=wordpress
    entrypoint: /var/www/html/wp-content/plugins/wordlift/.docker-custom-entrypoint.sh

  nginx:
    image: nginx:1.21.6
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
    environment:
      NGINX_HOST: wordpress
      NGINX_SERVER_NAME: wordlift.localhost
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_SERVER_NAME' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/wordpress.conf && nginx -g 'daemon off;'"

  cli:
    image: wordpress:cli-2.6.0
    depends_on:
      - db
    user: xfs
    volumes:
      - wordpress-data-${WORDPRESS_VERSION:-5.5.0}:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/wordlift
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    tty: true

volumes:
  db-data-4.4.0:
  wordpress-data-4.4.0:
  db-data-4.7.0:
  wordpress-data-4.7.0:
  db-data-5.0.0:
  wordpress-data-5.0.0:
  db-data-5.3.0:
  wordpress-data-5.3.0:
  db-data-5.4.0:
  wordpress-data-5.4.0:
  db-data-5.5.0:
  wordpress-data-5.5.0:
